#!/usr/bin/env python

import argparse
import FWCore.ParameterSet.Config as cms
import pickle


parser = argparse.ArgumentParser(description='Displays CMSSW configuration stored in CRAB PSet.pkl file.')

parser.add_argument('input_file', metavar='PKL_FILE', help='Pickle file to read. Crab stores the file in the input subdirectory of the submission working directory under the name PSet.pkl')

args=parser.parse_args()

process = pickle.load(open(args.input_file))

print process.dumpConfig()
