#!/usr/bin/env python

import os.path
import os
from email.mime.text import MIMEText
from email.mime.text import MIMEText
from subprocess import Popen, PIPE
import sys

mailbox = "~shearsop/work/.shears-mailbox"
From = 'shearsop@cern.ch'
To = 'cms-shears-ntuple-announcement@cern.ch'

def main():
	try:
		mailbox_ = os.path.expanduser(mailbox)
		mailbox_tmp = mailbox_ + '#'
		os.rename(mailbox_, mailbox_tmp)
	except OSError, e:
		if not os.path.isfile(mailbox_):
			sys.stdout.write("No mail to send.\n")
			return
		else:
			raise
	try:
		f = open(os.path.expanduser(mailbox_tmp), "r")
		msg = MIMEText(f.read())
		msg['Subject'] = 'Boabab production report'     
		msg['From'] = From
		msg['To'] = To
		p = Popen(["/usr/sbin/sendmail", "-t", "-oi"], stdin=PIPE)
		p.communicate(msg.as_string())
		print "Email sent to %s" % To
	except IOError, e:
		sys.stderr.write("\n%s\n" % e.message)
	finally:
		f.close()

if __name__ == '__main__':
	main()
